import { enableProdMode } from '@angular/core';
import { Component } from '@angular/core';

import { environment } from '../environments/environment';

if (environment.production) {
  enableProdMode();
}

function log(className) {
  console.log(className)
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  title = 'NG 6 Apps';
 
  constructor() {
    this.aSimpleMethod("This statement was generated by the constructor ", this.aSimpleMethod(5, 2));
  }

  aSimpleMethod(a, b) {
    // console.log("what's the answer?");
    return a*a
  } 
}
