import { Component } from '@angular/core';

function log(target, name, descriptor) {
  console.log(target, name, descriptor)

  // store the original function in a var. 
  const original = descriptor.value;

  // do some manipulations with the descriptor.value
  descriptor.value = (...args) => {    
    console.log("Arguments ", args, "were passed into this function.")
    const result = original(this, args) 
    console.error("the results of this function is ", result)
  }

  // return the descriptor
  // original();
  return descriptor;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  title = 'NG 6 Apps';
 
  constructor() {
    this.aSimpleMethod("this statement was generated by the construction", this.aSimpleMethod(5));
  }

  @log
  aSimpleMethod(a) {
    // console.log("what's the answer?");
    return a*a;    
  }
}
